baseURL = "https://churious.github.io/"
title = "Churious"
languageCode = "ko-kr"

[params]
  defaultTheme = "auto"
  description = "Crafting with Curiosity"
  author = { name = "Churious" }
  
  # 블로그 글 설정
  ShowReadingTime = true
  ShowShareButtons = false
  
  # 로고 설정
  label = { text = "Churious", icon = "/images/logo.svg", iconHeight = 35 }

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

